import {db,doc,setDoc,onSnapshot,collection,serverTimestamp,autoFormatMmSs,setupUI,setThemeFromSwitch,parseMmSsToSeconds,secondsToMmSs,colorForId,countdownClass,countdownText,esc} from './shared.js';
window.setThemeFromSwitch=setThemeFromSwitch;setupUI();
let playerUnsub=null,sentRallies={},currentMarchTime=localStorage.getItem('marchTime')||'';
autoFormatMmSs(document.getElementById('loginMarchTime'));autoFormatMmSs(document.getElementById('marchAdjustInput'));
const linkedName=()=>localStorage.getItem('playerName')||'';
function showLogin(){document.getElementById('loginView').classList.remove('hidden');document.getElementById('playerView').classList.add('hidden')}
function showPlayer(){document.getElementById('loginView').classList.add('hidden');document.getElementById('playerView').classList.remove('hidden');document.getElementById('welcomeName').textContent=linkedName()||'Player';document.getElementById('marchAdjustInput').value=currentMarchTime||'00:00';listenToMyPlayer();renderRallies()}
function listenToMyPlayer(){const name=linkedName();if(!name)return;if(playerUnsub)playerUnsub();playerUnsub=onSnapshot(doc(db,'players',name),snap=>{if(!snap.exists()){localStorage.removeItem('playerName');localStorage.removeItem('marchTime');currentMarchTime='';showLogin();return}const d=snap.data();if(d.marchTime&&d.marchTime!==currentMarchTime){currentMarchTime=d.marchTime;localStorage.setItem('marchTime',currentMarchTime);document.getElementById('marchAdjustInput').value=currentMarchTime}renderRallies()})}
window.loginPlayer=async()=>{const name=document.getElementById('loginName').value.trim(),marchTime=document.getElementById('loginMarchTime').value.trim();if(!name){alert('Enter player name.');return}if(parseMmSsToSeconds(marchTime)===null){alert('Enter march time as MM:SS.');return}localStorage.setItem('playerName',name);localStorage.setItem('marchTime',marchTime);currentMarchTime=marchTime;await setDoc(doc(db,'players',name),{name,marchTime,updatedAt:serverTimestamp()},{merge:true});showPlayer()};
window.adjustMarch=d=>{let s=parseMmSsToSeconds(document.getElementById('marchAdjustInput').value);if(s===null)s=0;s=Math.max(0,s+Number(d));document.getElementById('marchAdjustInput').value=secondsToMmSs(s);document.getElementById('marchStatus').textContent='Not saved'};
window.updateMarch=async()=>{const name=linkedName(),v=document.getElementById('marchAdjustInput').value.trim();if(parseMmSsToSeconds(v)===null){alert('Enter march time as MM:SS.');return}currentMarchTime=v;localStorage.setItem('marchTime',v);await setDoc(doc(db,'players',name),{name,marchTime:v,updatedAt:serverTimestamp()},{merge:true});document.getElementById('marchStatus').textContent='Saved';renderRallies()};
function renderRallies(){const el=document.getElementById('activeRallies');if(!el)return;const now=Date.now();const rows=Object.entries(sentRallies).map(([id,r])=>({id,...r})).filter(r=>Number(r.playerSendEndMs)&&r.playerId===linkedName()).sort((a,b)=>Number(a.playerSendEndMs)-Number(b.playerSendEndMs)).map(r=>{const sec=Math.ceil((Number(r.playerSendEndMs)-now)/1000),color=r.color||colorForId(r.sourceRallyId||r.id),cls=countdownClass(sec),timerColor=cls?'':`style="color:${color}"`;return `<div class="rally-row" style="color:${color}"><div class="rally-name">${esc(r.name)}</div><div class="rally-countdown ${cls}" ${timerColor}>${countdownText(sec)}</div></div>`});el.innerHTML=rows.join('')||`<div class="empty-state">No active rallies.</div>`}
window.addEventListener('load',()=>{const n=localStorage.getItem('playerName'),m=localStorage.getItem('marchTime');if(n)document.getElementById('loginName').value=n;if(m)document.getElementById('loginMarchTime').value=m;currentMarchTime=m||'';if(n&&m)showPlayer();else showLogin()});
onSnapshot(collection(db,'sentRallies'),s=>{sentRallies={};s.forEach(d=>sentRallies[d.id]=d.data());renderRallies()});setInterval(renderRallies,1000);
